const constants = {
  MAIN_REF: "MAIN_REF",
  MESSAGE: "MESSAGE",
  //
  SEARCH_SCROLL_REQUEST: "SEARCH_SCROLL_REQUEST",
  SCROLL_SUCCESS: "SCROLL_SUCCESS",
  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  //
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_IN_SOC: "SIGN_IN_SOC",
  RESET_PASS: "RESET_PASS",
  USER_CHECK: "USER_CHECK",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  USER_CHECK_SUCCESS: "USER_CHECK_SUCCESS",
  USER_CHECK_FAILED: "USER_CHECK_FAILED",
  //
  SUBTITLES_REQUEST: "SUBTITLES_REQUEST",
  SUBTITLES_SUCCESS: "SUBTITLES_SUCCESS",
  //
  FOCUS_CAPTIONS: "FOCUS_CAPTIONS",
  TEXT_TRANSLATE_REQUEST: "TEXT_TRANSLATE_REQUEST",
  TEXT_TRANSLATE_SUCCESS: "TEXT_TRANSLATE_SUCCESS",
  //
  SET_VIDEO_LANGUAGE: "SET_VIDEO_LANGUAGE",
  DEL_VIDEO_LANGUAGE: "DEL_VIDEO_LANGUAGE",
  //
  VIDEO_LANG_REQUEST: "VIDEO_LANG_REQUEST",
  VIDEO_LANG_SUCCESS: "VIDEO_LANG_SUCCESS",
  LANGUAGES_REQUEST: "LANGUAGES_REQUEST",
  LANGUAGES_SUCCESS: "LANGUAGES_SUCCESS",
  SET_LANGUAGE: "SET_LANGUAGE",
  //
  SAVE_PHRASE_REQUEST: "SAVE_PHRASE_REQUEST",
  SAVE_PHRASE_SUCCESS: "SAVE_PHRASE_SUCCESS",
  FETCH_PHRASES_REQUEST: "FETCH_PHRASES_REQUEST",
  FETCH_VIDEO_PHRASES_REQUEST: "FETCH_VIDEO_PHRASES_REQUEST",
  FETCH_VIDEO_PHRASES_SUCCESS: "FETCH_VIDEO_PHRASES_SUCCESS",
  FETCH_PHRASES_SUCCESS: "FETCH_PHRASES_SUCCESS",
  SEARCH_PHRASES_REQUEST: "SEARCH_PHRASES_REQUEST",
  SORT_PHRASES_REQUEST: "SORT_PHRASES_REQUEST",
  PHRASE_COMMENT: "PHRASE_COMMENT",

  DELETE_PHRASE_REQUEST: "DELETE_PHRASE_REQUEST",
  WATCH_VIDEO: "WATCH_VIDEO",
  //
  SAVE_TO_DB_REQUEST: "SAVE_TO_DB_REQUEST",
  SAVE_TO_DB_SUCCESS: "SAVE_TO_DB_SUCCESS",
  USER_ID_REQUEST: "USER_ID_REQUEST",
  USER_ID_SUCCESS: "USER_ID_SUCCESS",
  GET_VIDEO_LANGUAGE_REQUEST: "GET_VIDEO_LANGUAGE_REQUEST",
  GET_VIDEO_LANGUAGE_SUCCESS: "GET_VIDEO_LANGUAGE_SUCCESS",
  GET_VIDEO_LANGUAGE_FETCHED: "GET_VIDEO_LANGUAGE_FETCHED",
  GET_VIDEO_LANGUAGE_ERROR: "GET_VIDEO_LANGUAGE_ERROR",
  //
  CATEG0RIES_FETCHED: "CATEG0RIES_FETCHED",
  CATEG0RIES_SUCCESS: "CATEG0RIES_SUCCESS",
  SUGGESTED_FETCHED: "SUGGESTED_FETCHED",
  SUGGESTED_SUCCESS: "SUGGESTED_SUCCESS",
  SUGGESTED_PAGINATION_FETCHED: "SUGGESTED_PAGINATION_FETCHED",
  SUGGESTED_PAGINATION_SUCCESS: "SUGGESTED_PAGINATION_SUCCESS",
  //
  GET_VIEWED_REQUEST: "GET_VIEWED_REQUEST",
  GET_VIEWED_FETCHED: "GET_VIEWED_FETCHED",
  GET_VIEWED_SUCCESS: "GET_VIEWED_SUCCESS",
  GET_VIEWED_ERROR: "GET_VIEWED_ERROR",
  GET_VIEWED_PAGINATION_REQUEST: "GET_VIEWED_PAGINATION_REQUEST",
  GET_VIEWED_PAGINATION_FETCHED: "GET_VIEWED_PAGINATION_FETCHED",
  GET_VIEWED_PAGINATION_SUCCESS: "GET_VIEWED_PAGINATION_SUCCESS",
  GET_VIEWED_PAGINATION_ERROR: "GET_VIEWED_PAGINATION_ERROR",
  //
  SHEETS_PAGINATION_REQUEST: "SHEETS_PAGINATION_REQUEST",
  SHEETS_PAGINATION_FETCHED: "SHEETS_PAGINATION_FETCHED",
  SHEETS_PAGINATION_SUCCESS: "SHEETS_PAGINATION_SUCCESS",
  SHEETS_PAGINATION_ERR: "SHEETS_PAGINATION_ERR",
};

export default constants;
